name: Build (Linux)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_linux:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Generate build system
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="" -DLIBCPUID_ENABLE_TESTS=ON

    - name: Build
      run: cmake --build build

    - name: Run cpuid_tool
      run: |
        ./build/cpuid_tool/cpuid_tool --save=- --all
        sudo ./build/cpuid_tool/cpuid_tool --rdmsr-raw --rdmsr

    - name: Run tests
      run: |
        make -C build consistency
        make -C build test-old

    - name: Install
      run: cmake --install build
      env:
        DESTDIR: ${{ github.workspace }}/installdir
